[package]
name = "nndb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
anyhow = "1.0.70"
async-trait = "0.1.68"
bytemuck = "1.13.1"
chrono = "0.4.24"
crc32fast = "1.3.2"
futures = "0.3.28"
image = { version = "0.24.6" }
image-match = { git = "https://github.com/alt-text-org/image-match-rs", version = "0.1.0", features = ["img", "image", "num"] }
itertools = "0.10.5"
maud = { version = "0.24.0", features = ["actix-web", "actix-web-dep"] }
md-5 = "0.10.5"
num_enum = "0.6.0"
once_cell = "1.17.1"
rayon = "1.7.0"
regex = "1.7.3"
rusqlite = { version = "0.29.0", features = ["chrono", "bundled"] }
tokio = { version = "1.27.0", features = ["sync", "rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-actix-web = "0.7.3"
tracing-subscriber = "0.3.16"
walkdir = "2.3.3"
