[package]
name = "nndb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
bytemuck = "1.13.1"
chrono = "0.4.24"
image = { version = "0.24.6" }
image-match = { git = "https://github.com/alt-text-org/image-match-rs", version = "0.1.0", features = ["img", "image", "num"] }
md-5 = "0.10.5"
num_enum = "0.6.0"
once_cell = "1.17.1"
rayon = "1.7.0"
rusqlite = { version = "0.29.0", features = ["chrono", "bundled"] }
tokio = { version = "1.27.0", features = ["sync"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
walkdir = "2.3.3"
