# Default application config

# Url to database
db_url = "test.db"

# Testing mode: copy files from input to element pool instead of deleting
testing_mode = true
 
# If true, files in input_folder will be scanned periodically
# Otherwise, import can be triggered manually in dashboard
auto_scan_files = false

# Set max log level
# - off
# - error
# - warn
# - info
# - debug
# - trace
log_level = "info"

# IP address to bind server to
bind_address = "0.0.0.0"

# Server port
port = 8080

# File to write logs
log_file = "log.txt"

# Directory that will be scanned to find new element files
input_folder = "res"


# Directory where renamed element files will be placed
[element_pool]
# URLs must include trailing slash
url = "/pool/"
# Path to physical folder
path = "pool"
# Serve from nndb
serve = true


# Store and serve thumbnails from this folder
[thumbnails_folder]
url = "/thumbs/"   
path = "thumbs"
serve = true


# Folder with miscellaneous static files  
[static_folder]
url = "/static/"
path = "static"
serve = true

